### ISSUE TITLE
Invalid SemVer Version

### ISSUE THREAD

**Issue by njt1982** [TradingPal/react-native-highcharts#106]
https://github.com/TradingPal/react-native-highcharts/blob/1c45360bf195fce618f87ea8f97e6aeabaf49086/package.json#L3

Yarn/NPM does not like adding this package via github as `1.1` is not valid SemVer?

**Comment by BernaLang** [comment]
This is fixed in my pull request #96 .

**Comment by njt1982** [comment]
As this is fixed in #96 I will close this.
