### ISSUE TITLE
show charts

### ISSUE THREAD

**Issue by leileizhu** [TradingPal/react-native-highcharts#13]
i use it on android,but i cant find chart on my app,it just blank,

**Comment by jonrh** [comment]
Hi @leileizhu, thanks for submitting the issue! Could you please tell us a little more so we might be able to help you? For example: could you show us the code you are using or better yet, a sample React Native repository we could take a look at?

**Comment by leileizhu** [comment]
sorry.....it's my fault,i convert the date wrong.

**Comment by jonrh** [comment]
No worries, happy it turned out okay! If this one is resolved we would appreciate if you could close it, to keep things tidy. If you run into any other issues please feel free to let us know and create another issue 😁
