### ISSUE TITLE
Unexpected token error with latest build.

### ISSUE THREAD

**Issue by mcorway** [TradingPal/react-native-highcharts#14]
Hi, I was using react-native-chart-view for some time on an app I've been developing for a few months now. A problem came up when I tried to do a release build, the charts would not show up and I saw in your closed issues list, that was a previous problem. So I updated to react-native-highcharts, latest version. I am also on React-Native build 0.42, but my app fails immediately with this error:

![screen shot 2017-03-14 at 2 48 49 pm](https://cloud.githubusercontent.com/assets/6304314/23917356/5e4f375a-08c5-11e7-9109-e6be59d07c9a.png)

This happens immediately when the App runs. I do not believe it to be my config, although my config does contain a function (but it comes from an outside source, the function must remain in).

Any help?

**Comment by mcorway** [comment]
Sorry about closing the issue, was by mistake.

**Comment by Infinity0106** [comment]
I think I found the error in line 44 in let end before it end with a , it should end with ; but I already commit the fix, can you try it?

**Comment by mmazzarolo** [comment]
Can confirm, it's the comma!

**Comment by hongmaoxiao** [comment]
same as
