### ISSUE TITLE
Implementing HighStock example

### ISSUE THREAD

**Issue by tomerf8** [TradingPal/react-native-highcharts#2]
I'm trying to implement the HighCharts demo at:
https://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/candlestick-and-volume/

In this example there are 2 series of data, styling is a bit different
* I'm using a local data file.

I'm getting a blank screen

**Comment by donaldmorton** [comment]
Highstock module is not included by default on this module but you can make a small change to do so,
you have to modify the default web template located at the `this.state.init`from react-native-ChartView.js try replacing line 103,
`<script src="https://code.highcharts.com/highcharts.js"></script>`
with
`                        <script src="http://code.highcharts.com/stock/highstock.js"></script>
`

**Comment by tomerf8** [comment]
Thanks. It's solves the problem. 

It's a bit ugly of course, but it's possible to duplicate the ChartView component and export a HighStock version.

**Comment by donaldmorton** [comment]
it would be a better idea to add a prop for using highstock, it could look like this:
` <ChartView style={{height:300}} config={conf} useHighstock={true}></ChartView>`
