### ISSUE TITLE
Commercial application with Highcharts

### ISSUE THREAD

**Issue by tanotify** [TradingPal/react-native-highcharts#20]
Do I need purchase any license for using react-native-highcharts in my application which I develop for both iOS and Android devices?

**Comment by jonrh** [comment]
**Technically**: No
**Legally**: Yes

Please see [license prices here](https://shop.highsoft.com/highcharts), Highsoft has different types of licenses to suit most commercial use cases.

**Comment by tanotify** [comment]
@jonrh , so and what case suits me most? Highcharts Single Developer?

**Comment by jonrh** [comment]
@tanotify If you are a single developer then yes the Highcharts Single Developer $410 would be most suitable, $595 if you want premium support. You may also be eligible for the *High-five Licence* at $50 if you're a startup in it's early phases. I'm sure Highsoft would also be willing to help you pick the most suitable option given your situation. Hope it helps!
