### ISSUE TITLE
The font on ios is too small

### ISSUE THREAD

**Issue by HyperSimon** [TradingPal/react-native-highcharts#24]
| on Android | on IOS |
|:--:|:--:|
|![screenshot_1493785327](https://cloud.githubusercontent.com/assets/9377192/25648131/24443d78-2ffb-11e7-849d-6221124ce382.png)|![simulator screen shot 2017 5 3 12 20 44](https://cloud.githubusercontent.com/assets/9377192/25648123/0fdcb3a6-2ffb-11e7-8d75-1641612a65e5.png)|

**Comment by njt1982** [comment]
@HyperSimon Did you solve this?

**Comment by sphism** [comment]
Can't this just be styled with css?

**Comment by sphism** [comment]
I managed to fix this yesterday by setting some things in the highcharts options. Not sure if that would make the android fonts huge, i guess you might need to target ios with different options.

@HyperSimon The options that fixed it were:

````
      chart: {
      ...
      },
      xAxis: {
        ...
        labels: {
          ...
          style: {
            fontSize: 24,
          },
        },
      },
      yAxis: {
        ...
        labels: {
          style: {
            fontSize: 24,
          },
        },
      },
      legend: {
        ...
        itemStyle: {
          fontSize: 32,
        },
      },
````

**Comment by HyperSimon** [comment]
see https://github.com/TradingPal/react-native-highcharts/pull/25
