### ISSUE TITLE
Cannot use Highcharts.setOptions

### ISSUE THREAD

**Issue by vincejah** [TradingPal/react-native-highcharts#30]
I am trying to set global Option to Highcharts
`
Highcharts.setOptions({
  global: {
    useUTC: false
 }
});
`

I get the following error: `Highcharts.setOptions is not a function`

What am I doing wrong

**Comment by donaldmorton** [comment]
It does't support global options, but it could be a nice thing to add

**Comment by 532878340** [comment]
+1

**Comment by luisfmsouza** [comment]
I've submitted the addition of options in the PR #52

Can you check it @developtradingpal ?

**Comment by Infinity0106** [comment]
done

thanks for the PR @luisfmsouza
