### ISSUE TITLE
Tooltip not visible

### ISSUE THREAD

**Issue by anupkale1984** [TradingPal/react-native-highcharts#36]
When i see on simulator, i am able to see tooltip as expected on cursor click. But when with same build on device i touch , pint gets highlighted but does not show any tooltip.

**Comment by justinlok** [comment]
+1

**Comment by ismjt** [comment]
i get the same problem of Tooltip, it does not work with android release app! and here is my toptip node config:
tooltip: {
                            formatter() {
                                return `<span><b>${this.series.name}</b><br/>
                                        ${Highcharts.numberFormat(this.y, 2)} mg/L</span>`;
                            }
                        }

how can i fix it?

**Comment by sreejithqb** [comment]
Instead of using "Highcharts.numberFormat" method,  use JS toString() method to convert the number or date into string. It will work

**Comment by ecsreejith** [comment]
Instead of using "Highcharts.numberFormat" method, use JS toString() method to convert the number or date into string. It will work

**Comment by justinlok** [comment]
@ecsreejith thanks, that works!

**Comment by ismjt** [comment]
@ecsreejith thanks a lot!

**Comment by milosh86** [comment]
It also works if you reference it from window object, i.e. window.Highcharts.numberFormat() or window.Highcharts.dateFormat()
