### ISSUE TITLE
Not working on real device

### ISSUE THREAD

**Issue by capurunep** [TradingPal/react-native-highcharts#4]
Hi,
I am evaluating react-native-highcharts. It works fine in emulator however its not working on real device. I tried with Samsung-Android.
Could you please suggest how to make it work on real device..

Best regards,
Puru

**Comment by Infinity0106** [comment]
we had the same problem we added domStorageEnable={true} on the webview tag, try getting the latest version and try to exportit

**Comment by capurunep** [comment]
Hi,
I am using ChartView..will it work on ChartView as well? I tried with this one and still shows html text on mobile device instead of chart. I used  domStorageEnable attribute as:
 <ChartView style={{height:250,marginTop:10}} config={conf} domStorageEnable={true}></ChartView>

and also set:
 exporting: {
                enabled: true
            }

Thanks,
Puru

**Comment by donaldmorton** [comment]
any error log ?

**Comment by jonrh** [comment]
I'm having the same issue on iOS. In my case I was using v0.0.1 (named *react-native-chart-view* back then) and it worked fine until recently. I have not been able to figure out what changed.

I tried upgrading to *react-native-highcharts* v0.1.1 but the issue remains. I also tried the latest version in the GitHub repository but to no avail. It works correctly in the simulator and when built for Debug (I'm doing an iOS app). What does not work is when the app is built for Release. I have not been able to find any error logs. If I figure something out I'll update or comment again in this issue.

**Comment by jinxac** [comment]
its working fine for me on IOS actually.

**Comment by jonrh** [comment]
@jinxac Does your Highcharts configuration object have any functions?

**Comment by jinxac** [comment]
I havent use any functions yet.. just read your comment and see that issue comes while using functions

**Comment by donaldmorton** [comment]
Hi, you can use this technique to debbug webviews on running devices this could give us more information on what's going on http://stackoverflow.com/questions/6508313/javascript-console-log-in-an-ios-uiwebview

**Comment by edelweiss88** [comment]
This problem actual for me. I added domStorageEnable={true}, but result show html text

**Comment by edelweiss88** [comment]
I update highcharts and added domStorageEnable={true}. Now application work only in debug release.

**Comment by cgcanceran** [comment]
Same issue I've encountered, react-native-highcharts 0.1.1 is working fine in emulator and debug release but not in the signed release.. Is there anyone knows the solution for this?

**Comment by Noiwex** [comment]
It happens because your config has functions. While compiling in Release mode it uses different webpack optimization config, resulting in code being completely screwed in unexpected way for this module.

I mean, look at this:

```
var config = JSON.stringify(this.props.config, function (key, value) {//create string of json but if it detects function it uses toString()
    return (typeof value === 'function') ? value.toString() : value;
});

config = config.replace(/\\n/g, " ");//remove \n in string = ""
config = config.replace(/\"([^(\")"]+)\":/g, "$1: ");//remove {"chart":"chart"} = {chart:"chart"}
config = config.replace(/\"function/g, "function");//remove {chart:"function ...} = {chart:function ...}
config = config.replace(/}\"/g, "}");//remove {chart:function(){}"} = {chart:function(){}} 
```

It's a fucking mess.

**Comment by jonrh** [comment]
@Noiwex Thanks for your input. This is indeed what I suspect is the root cause. Could you please create a pull request to handle it better? Or how would you approach solving this issue?

**Comment by nkov** [comment]
@Noiwex @jonrh You were right, it was this 'parsing' that caused the issue in iOS release mode (at least for me). My attached pr (#9) fixes this issue by parsing it a different way.

**Comment by jonrh** [comment]
Awesome, thanks @nkov! I'll try to get around to testing your implementation as soon as I can. Thanks again 👏

**Comment by Noiwex** [comment]
I've modified module to accept string as config, but thanks for PR, @nkov

**Comment by Noiwex** [comment]
Also, I might drop in some hacks made by me to make this module work properly on iOS in various situations.

**Comment by Noiwex** [comment]
Resolved.

**Comment by d12544** [comment]
having the same issue for waterfall chart. works fine on emulator but not on physical device.
