### ISSUE TITLE
About last viewport commit and main file on package.json

### ISSUE THREAD

**Issue by gusbueno** [TradingPal/react-native-highcharts#41]
Hi dude!,

Thanks for your last commit adding the viewport meta but there is a problem. The problem is that you only added this meta on App/index.js but your package.json define your react-native-highcharts.js as the main file and this file hasn't the meta tag.

Could you add the meta tag in the react-native-highcharts.js, please?
and can we disable the resize of the webview with user-scalable=0?

the meta would be:
`<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />`

Thanks a lot!

**Comment by ChrisTolmeijer** [comment]
`<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0" />`

**Comment by Infinity0106** [comment]
Done, and sorry i have been very busy and not checking the repo lately XD
