### ISSUE TITLE
Chart sizing is completely different on iOS vs Android

### ISSUE THREAD

**Issue by jslok** [TradingPal/react-native-highcharts#47]
On any iOS device simulator, the chart text and axis are all very very tiny (no real device to test on). The chart with the exact same code and data looks fine on any Android I try. The first picture is on an iPhone 7 (simulator) and second screenshot is on a Galaxy S6.

Has anybody else run into this issue? Any ideas how to fix it? I could not find a scaling option.

![simulator screen shot sep 20 2017 11 35 22 pm](https://user-images.githubusercontent.com/22921326/30682212-90314ba4-9e5d-11e7-8d32-2959a2eb6b5a.png)
![screenshot_20170920-233545](https://user-images.githubusercontent.com/22921326/30682217-9212dc44-9e5d-11e7-8757-62768a73b3f4.png)

**Comment by luisfmsouza** [comment]
It's related to this one, I think: https://github.com/TradingPal/react-native-highcharts/issues/41

**Comment by luisfmsouza** [comment]
We can close this issue @Infinity0106
