### ISSUE TITLE
Expo compatibility

### ISSUE THREAD

**Issue by BenjaminWatts** [TradingPal/react-native-highcharts#68]
Hi - I really struggled to get this to install and work with Expo - so I created a very simple Webview oriented app that seems to work well.

[https://github.com/BenjaminWatts/react-native-highchart-webview](url)

Comments much appreciated!

**Comment by rture** [comment]
I was getting a problem too but it requires me to install react-native-svg after that it worked fine. 
Even it is working ok now, I don't think it will not work in offline mode.
