### ISSUE TITLE
Update graph less than millisecond?

### ISSUE THREAD

**Issue by bitabs** [TradingPal/react-native-highcharts#71]
I'm currently getting data really fast, less than milliseconds. Is it possible to get that smooth animation less than milliseconds?

There is currently a 1-second interval between each data point. But for retrieving ECG data, I don't need the interval. Is this possible?

**Comment by YaweiZhang-930** [comment]
@NaseebullahSafi hi I'm having a same issue. Currently I'm getting data really fast which is 30 milliseconds. And the performance is getting really back. Would you mind sharing your ideas?
