### ISSUE TITLE
waterfall chart not showing 

### ISSUE THREAD

**Issue by d12544** [TradingPal/react-native-highcharts#88]
var conf1={
        chart: {
          type: 'waterfall',
          animation: Highcharts.svg,
      },

      title: {
          text: 'Highcharts Waterfall'
      },

      xAxis: {
          type: 'category'
      },

      yAxis: {
          title: {
              text: 'USD'
          }
      },

      legend: {
          enabled: false
      },

      tooltip: {
          pointFormat: '<b>${point.y:,.2f}</b> USD'
      },

      series: [{
        upColor: 'green',
        color: 'blue',
          data: [{
              name: 'Start',
              y: 120000
          }, {
              name: 'Product Revenue',
              y: 569000
          }, {
              name: 'Service Revenue',
              y: 231000
          }],
          dataLabels: {
              enabled: true,
              formatter: function () {
                  return Highcharts.numberFormat(this.y / 1000, 0, ',') + 'k';
              },
              style: {
                  fontWeight: 'bold'
              }
          },
                
              }]
    };

return (
     <ChartView style={{height:300}} config={conf1}  stock={false}></ChartView>
              );

**Comment by pavaleanuL** [comment]
Could you please tell me how you solved this issue.
Thanks.

**Comment by d12544** [comment]
@pavaleanuL 

Replace this.state in react-native-highcharts/app/index.js and react-native-highcharts.js with the below code.



`this.state={
            init:`<html>
                    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0" />
                    <style media="screen" type="text/css">
                    #container {
                        width:100%;
                        height:100%;
                        top:0;
                        left:0;
                        right:0;
                        bottom:0;
                        position:absolute;
                        user-select: none;
                        -webkit-user-select: none;
                    }
                    </style>
                    <head>
                         <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://code.highcharts.com/highcharts.js"></script>
						<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
						<script src="https://code.highcharts.com/highcharts-more.js"></script>
						<script src = "https://code.highcharts.com/modules/heatmap.js"></script>  
						<script src = "https://code.highcharts.com/modules/treemap.js"></script> 
                        <script src="https://code.highcharts.com/modules/exporting.js"></script>
                       
                        <script>
                        $(function () {
                            Highcharts.setOptions(${JSON.stringify(this.props.options)});
                            Highcharts.${this.props.stock ? 'stockChart' : 'chart'}('container', `,
            end:`           );
                        });
                        </script>
                    </head>
                    <body>
                        <div id="container">
                        </div>
                    </body>
                </html>`,
            Wlayout:{
                height:win.height,
                width:win.width
            }
        }`
